[project]
name = "duckdb-dev"
version = "0.1.0"
description = "Explore the ability of duckdb"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.0",
    "pandas>=2.2.3",
]
